# Generated by Django 6.1 on 2026-08-24 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='اسم فروشگاه')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='شرح فروشگاه')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='accounts.seller')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='اسم محصول')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='موجودی')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='شرح محصول')),
                ('image', models.ImageField(upload_to='product-avatar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.store')),
            ],
        ),
    ]
